# Default values for the chart
image:
  repository: 207567795251.dkr.ecr.eu-central-1.amazonaws.com/devops_task/main
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 8888
  nodePort: 30180 

replicaCount: 1
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi

imagePullSecrets:
  - name: ecr-secret

namespace: jenkins # Add a default namespace