{
 "title": "RS School task 8 basic metrics",
 "description": "RS School task 8 basic metrics",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Node_LA_1|5|15",
   "type": "timeseries",
   "description": "Grafana board for task 8 with basic metrics",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "node_load1", "legendFormat": "__auto" },
    { "expr": "node_load5", "legendFormat": "__auto" },
    { "expr": "node_load15", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Node_Free_RAM",
   "type": "timeseries",
   "description": "Grafana board for task 8 with basic metrics",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "node_memory_MemFree_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Node_CPU_Util",
   "type": "timeseries",
   "description": "Grafana board for task 8 with basic metrics",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "targets": [
    {
     "expr": "100 * avg(1 - rate(node_cpu_seconds_total{mode=\"idle\"}[2m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}