apiVersion: 1
contactPoints:
    - orgId: 1
      name: AWS SNS
      receivers:
        - uid: aws_sns_main
          type: email
          settings:
            addresses: devopscoursevasylkh@gmail.com
            singleEmail: false
          disableResolveMessage: false

groups:
    - orgId: 1
      name: 1m_group
      folder: Basic
      interval: 1m
      rules:
        - uid: ae6tomwlei5tsc
          title: Node_LA_5
          condition: E
          data:
            - refId: A
              relativeTimeRange:
                from: 1800
                to: 0
              datasourceUid: PBFA97CFB590B2093
              model:
                adhocFilters: []
                datasource:
                    type: prometheus
                    uid: PBFA97CFB590B2093
                disableTextWrap: false
                editorMode: builder
                expr: node_load1
                fullMetaSearch: false
                includeNullMetadata: true
                interval: ""
                intervalMs: 15000
                legendFormat: __auto
                maxDataPoints: 43200
                range: true
                refId: A
                useBackend: false
            - refId: B
              relativeTimeRange:
                from: 1800
                to: 0
              datasourceUid: PBFA97CFB590B2093
              model:
                adhocFilters: []
                datasource:
                    type: prometheus
                    uid: PBFA97CFB590B2093
                disableTextWrap: false
                editorMode: builder
                expr: node_load5
                fullMetaSearch: false
                includeNullMetadata: true
                interval: ""
                intervalMs: 15000
                legendFormat: __auto
                maxDataPoints: 43200
                range: true
                refId: B
                useBackend: false
            - refId: C
              relativeTimeRange:
                from: 1800
                to: 0
              datasourceUid: PBFA97CFB590B2093
              model:
                adhocFilters: []
                datasource:
                    type: prometheus
                    uid: PBFA97CFB590B2093
                disableTextWrap: false
                editorMode: builder
                expr: node_load15
                fullMetaSearch: false
                includeNullMetadata: true
                interval: ""
                intervalMs: 15000
                legendFormat: __auto
                maxDataPoints: 43200
                range: true
                refId: C
                useBackend: false
            - refId: D
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params: []
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - D
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: B
                intervalMs: 1000
                maxDataPoints: 43200
                reducer: last
                refId: D
                settings:
                    mode: ""
                type: reduce
            - refId: E
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 5
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - E
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: D
                intervalMs: 1000
                maxDataPoints: 43200
                refId: E
                type: threshold
          dashboardUid: ae68cei3f4f0gb
          panelId: 1
          noDataState: NoData
          execErrState: Error
          for: 1m
          annotations:
            __dashboardUid__: ae68cei3f4f0gb
            __panelId__: "1"
          labels:
            mode: test
          isPaused: false
          notification_settings:
            receiver: AWS SNS
        - uid: fe6tt04beopa8e
          title: Node_Free_RAM
          condition: D
          data:
            - refId: A
              relativeTimeRange:
                from: 1800
                to: 0
              datasourceUid: PBFA97CFB590B2093
              model:
                adhocFilters: []
                datasource:
                    type: prometheus
                    uid: PBFA97CFB590B2093
                disableTextWrap: false
                editorMode: builder
                expr: node_memory_MemFree_bytes
                fullMetaSearch: false
                includeNullMetadata: true
                instant: false
                interval: ""
                intervalMs: 15000
                legendFormat: __auto
                maxDataPoints: 43200
                range: true
                refId: A
                useBackend: false
            - refId: B
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params: []
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - B
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                reducer: last
                refId: B
                type: reduce
            - refId: D
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 210
                        type: lt
                      operator:
                        type: and
                      query:
                        params:
                            - C
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: C
                intervalMs: 1000
                maxDataPoints: 43200
                refId: D
                type: threshold
            - refId: C
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 0
                            - 0
                        type: gt
                      operator:
                        type: and
                      query:
                        params: []
                      reducer:
                        params: []
                        type: avg
                      type: query
                datasource:
                    name: Expression
                    type: __expr__
                    uid: __expr__
                expression: $B/1024/1024
                hide: false
                intervalMs: 1000
                maxDataPoints: 43200
                refId: C
                type: math
          dashboardUid: ae68cei3f4f0gb
          panelId: 2
          noDataState: NoData
          execErrState: Error
          for: 1m
          annotations:
            __dashboardUid__: ae68cei3f4f0gb
            __panelId__: "2"
          labels:
            mode: test
          isPaused: false
          notification_settings:
            receiver: AWS SNS
        - uid: de6ttgsod4r9ca
          title: Node_CPU_Util
          condition: C
          data:
            - refId: A
              relativeTimeRange:
                from: 1800
                to: 0
              datasourceUid: PBFA97CFB590B2093
              model:
                adhocFilters: []
                datasource:
                    type: prometheus
                    uid: PBFA97CFB590B2093
                disableTextWrap: false
                editorMode: code
                expr: 100 * avg(1 - rate(node_cpu_seconds_total{mode="idle"}[2m]))
                fullMetaSearch: false
                includeNullMetadata: true
                interval: ""
                intervalMs: 15000
                legendFormat: __auto
                maxDataPoints: 43200
                range: true
                refId: A
                useBackend: false
            - refId: B
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params: []
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - B
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                reducer: last
                refId: B
                type: reduce
            - refId: C
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 80
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - C
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: B
                intervalMs: 1000
                maxDataPoints: 43200
                refId: C
                type: threshold
          dashboardUid: ae68cei3f4f0gb
          panelId: 3
          noDataState: NoData
          execErrState: Error
          for: 1m
          annotations:
            __dashboardUid__: ae68cei3f4f0gb
            __panelId__: "3"
          labels:
            mode: test
          isPaused: false
          notification_settings:
            receiver: AWS SNS