apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "word-cloud-generator.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "word-cloud-generator.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "word-cloud-generator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "word-cloud-generator.selectorLabels" . | nindent 8 }}
    spec:
      imagePullSecrets:
        {{- range .Values.imagePullSecrets }}
        - name: {{ .name }}
        {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}