apiVersion: v1
kind: Service
metadata:
  name: {{ include "word-cloud-generator.fullname" . }}
  namespace: {{ .Values.namespace }} # Use the namespace variable
  labels:
    {{- include "word-cloud-generator.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      nodePort: {{ .Values.service.nodePort }}
  selector:
    {{- include "word-cloud-generator.selectorLabels" . | nindent 4 }}